services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: webapp
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Webapp
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U webapp -d Webapp" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: demo
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/Webapp
      SPRING_DATASOURCE_USERNAME: webapp
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8000:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge